# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'suspectwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SuspectWindow(object):
    def setupUi(self, SuspectWindow):
        SuspectWindow.setObjectName("SuspectWindow")
        SuspectWindow.resize(1064, 833)
        SuspectWindow.setToolTipDuration(4)
        self.centralwidget = QtWidgets.QWidget(SuspectWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(9, 15, 351, 391))
        self.label.setStyleSheet("image: url(:/images/BeckhamReets.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 400, 351, 391))
        self.label_2.setStyleSheet("image: url(:/images/DariusBecks.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(380, 10, 351, 391))
        self.label_3.setStyleSheet("image: url(:/images/IanMortez.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(740, 10, 351, 391))
        self.label_4.setStyleSheet("image: url(:/images/RamiroFlorez.png);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(390, 400, 351, 391))
        self.label_5.setStyleSheet("image: url(:/images/SarahManse.png);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(740, 400, 351, 391))
        self.label_6.setStyleSheet("image: url(:/images/KateLanches.png);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        SuspectWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SuspectWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1064, 37))
        self.menubar.setObjectName("menubar")
        SuspectWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SuspectWindow)
        self.statusbar.setObjectName("statusbar")
        SuspectWindow.setStatusBar(self.statusbar)

        self.retranslateUi(SuspectWindow)
        QtCore.QMetaObject.connectSlotsByName(SuspectWindow)

    def retranslateUi(self, SuspectWindow):
        _translate = QtCore.QCoreApplication.translate
        SuspectWindow.setWindowTitle(_translate("SuspectWindow", "MainWindow"))
import suspect_rc
